language: python
python:
  - "3.5"

os: 
  - linux

matrix:
  include:
  - os: osx
  language: generic
  env: PYTHON=3.5.1

before_install:
  - chmod +x ./tst/tst_dwnl.sh
  - chmod +x ./tst/tst_repr.sh

install: 
  - pip install pandas

script: 
  - ./tst/tst_dwnl.sh
  - ./tst/tst_repr.sh


