language: generic


matrix:
  include:
  - os: osx
  - os: linux
  language: generic
  

before_install:
  - chmod +x ./tst/tst_dwnl.sh
  - chmod +x ./tst/tst_repr.sh

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
     then apt-get --version ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; 
  then sudo apt-get install -y $(grep -vE '(^#|^$)' requirements.apt) ; fi
    

     #osx
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3 ; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then virtualenv venv -p python3; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source venv/bin/activate; fi

install: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
          then sudo pip install -r requirements.pip ; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; 
    then pip install -r requirements.pip ; fi

script: 
  - ./tst/tst_dwnl.sh
  - ./tst/tst_repr.sh


