language: python
python: 
  - "3.6"

os: 
  - linux
  - osx

before_install:
  - chmod +x tst_dwnl.sh
  - chmod +x tst_repr.sh

install: 
  - pip install pandas

script: 
  - ./tst/tst_dwnl.sh
  - ./tst/tst_repr.sh


