environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pandas"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - cmd: wget http://rapid-hub.org/data/angles_UCI_CS.csv
  - cmd: wget http://rapid-hub.org/data/angles_UCI_CS_out.csv

build: off

test_script:
  - ps: sh tst/tst_repr.sh